language: bash

services:
  - docker

before_install:
  - docker build -t philippvk/docker-freertos-sdl2:14.04 .
  - docker run philippvk/docker-freertos-sdl2:14.04 /bin/sh -c "echo 123"

script:
  - date

deploy:
  provider: script
  script: bash push2dockerhub.sh
  on:
    branch: master
