version: '3.3'
services:
  osx:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DHOST_OS=osx -DEMULATOR=true /tmp/project && tail -f /dev/null"
    volumes:
      - ${DIR}:/tmp/project:ro
      - ${DIR}/bin:/tmp/project/bin
    environment:
      - "DISPLAY=host.docker.internal:0.0"
  unix:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DHOST_OS=unix -DEMULATOR=true /tmp/project && tail -f /dev/null"
    volumes:
      - ${DIR}:/tmp/project:ro
      - ${DIR}/bin:/tmp/project/bin
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - "DISPLAY"
  win:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DHOST_OS=win -DEMULATOR=true /tmp/project && tail -f /dev/null"
    volumes:
      - ${DIR}:/tmp/project:ro
      - ${DIR}/bin:/tmp/project/bin
    environment:
      - "DISPLAY=host.docker.internal:0.0"
