version: '3.3'
services:
  darwin:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DINSIDE_DOCKER=true -DENABLE_CLANG_TIDY=ON /tmp/project && tail -f /dev/null"
    privileged: true
    volumes:
      - ${PROJECT_DIR}:/tmp/project:ro
      - ${PROJECT_DIR}/bin:/tmp/project/bin
    ports:
      - "2000:2000"
    environment:
      - "DISPLAY=host.docker.internal:0.0"
  linux:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DINSIDE_DOCKER=true -DENABLE_CLANG_TIDY=ON /tmp/project && tail -f /dev/null"
    privileged: true
    volumes:
      - ${PROJECT_DIR}:/tmp/project:ro
      - ${PROJECT_DIR}/bin:/tmp/project/bin
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "2000:2000"
    environment:
      - "DISPLAY"
  windows:
    image: "philippvk/docker-freertos-sdl2:14.04"
    command: /bin/bash -c "rm -rf /tmp/build && mkdir /tmp/build && cd /tmp/build && cmake -DINSIDE_DOCKER=true -DENABLE_CLANG_TIDY=ON /tmp/project && tail -f /dev/null"
    privileged: true
    volumes:
      - ${PROJECT_DIR}:/tmp/project:ro
      - ${PROJECT_DIR}/bin:/tmp/project/bin
    ports:
      - "2000:2000"
    environment:
      - "DISPLAY=host.docker.internal:0.0"
